build: off
shallow_clone: true
version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version
  - SET PATH=%APPDATA%\npm;%PATH%
  - npm install -g npm
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "0.12"
    - nodejs_version: "0.10"
    - nodejs_version: "0.8"
